spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  jwt:
    secret: ${JWT_ACCESS_SECRET_KEY}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.101:30306/hot_deal
    hikari:
      username: root
      password: ${MYSQL_DB_PASSWORD}
  sql:
    init:
      mode: always
  data:
    redis:
      repositories:
        enabled: false
management:
  endpoints:
    web:
      exposure:
        include: "health"