spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  jwt:
    secret: ${JWT_ACCESS_SECRET_KEY}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_DB_URL}
    hikari:
      username: root
      password: ${MYSQL_DB_PASSWORD}
  sql:
    init:
      mode: always
  data:
    redis:
      repositories:
        enabled: false
  kafka:
    consumer:
      bootstrap-servers: kafka.kafka.svc.cluster.local:9092
      group-id: order-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
management:
  endpoints:
    web:
      exposure:
        include: "health"